### ISSUE TITLE
✨ Backend: Implement JWE-based Authentication System

### ISSUE THREAD

**Issue by samiurprapon** [samiurprapon/Aether#178]
### ✨ Feature Request Overview
**Feature:**  
This project implements a JWE-based authentication system for secure user authentication in the server-side application. JWE (JSON Web Encryption) enhances the security of JWT tokens by encrypting their payload, making it significantly more difficult for attackers to manipulate or read sensitive information.

---

### 🔍 Priority
- High

---

## 📂 Scope

- [ ] 📱 Android
- [X] 🖥️ Backend
- [ ] 🖼️ Frontend
- [ ] 📝 Documentation

### 🎨 Design & Mockup
- N/A

---

### 💡 How it Will Work

- **Token Generation:**  
  User data (e.g., user ID, roles) is encoded into a JWT. Instead of signing the JWT alone, it is encrypted using JWE. This JWE token is then issued to the user for subsequent requests.

- **Token Decryption & Verification:**  
  When the server receives a JWE token, it decrypts it to extract the JWT. The JWT is then verified to ensure its authenticity and validity. If valid, the user is authenticated.

- **Middleware:**  
  A custom middleware is implemented to decrypt and verify the JWE tokens on protected routes, ensuring that only authenticated and authorized users can access these routes.

---

### 📘 Additional Context
- [RFC 7516: JSON Web Encryption (JWE)](https://tools.ietf.org/html/rfc7516)
- [JSON Web Token (JWT) Specification](https://datatracker.ietf.org/doc/html/rfc7519)
- [Node.js Crypto Documentation](https://nodejs.org/api/crypto.html)

**Comment by ayush1009208** [comment]
Hey @samiurprapon can you plzz assign this issue to me?
I have previous exeirience with jwt

**Comment by samiurprapon** [comment]
Hi @ayush1009208 , I'm trying to implement JSON Web Encryption,  not implementing JWT.  you can check [feat/auth](https://github.com/samiurprapon/Aether/tree/feat/auth) this branch, I already implemented JoseService for that.

**Comment by ayush1009208** [comment]
Ohhk @samiurprapon 
I will take a look...

**Comment by dsparrowm** [comment]
Can you assign this issue to me?, I am experienced in both JWT and JWE

**Comment by samiurprapon** [comment]
Fork https://github.com/samiurprapon/Aether/tree/feat/auth this branch to start with this issue

**Comment by dsparrowm** [comment]
> Fork https://github.com/samiurprapon/Aether/tree/feat/auth this branch to start with this issue

I'm having issues with running migrations on mysql database, it seems to reject my mysql password. Can you help out?

**Comment by samiurprapon** [comment]
please drop the error log here. @dsparrowm
