### ISSUE TITLE
[Feature Request] Implement Auth Pages 

### ISSUE THREAD

**Issue by samiurprapon** [samiurprapon/Aether#190]
### 🚀 Feature Request

**Description:**
We are looking to create a new **Auth Page** using **React**. This landing page will serve as the first point of contact for users, showcasing our product and encouraging user engagement.

## 📂 Scope

- [ ] 📱 Android
- [ ] 🖥️ Backend
- [X] 🖼️ Frontend
- [ ] 📝 Documentation

### 🎨 Design & Mockup:
![LoginPage](https://github.com/user-attachments/assets/52e442c3-22a1-40c0-b141-bf5022f3f8ef)

### 📋 Requirements:
1. **Light/Dark Mode**

### 🛠️ Tech Stack:
- React
- TypeScript

### 📝 Additional Context:
- You can offer different designs but keep this `eye image`

**Comment by samiurprapon** [comment]
@mayank-0789

**Comment by mayank-0789** [comment]
@samiurprapon  please assign this issue to me

**Comment by Anurag-singh-thakur** [comment]
please assign it to me

**Comment by samiurprapon** [comment]
Hey @Anurag-singh-thakur , I also assigned you here in this issue.

**Comment by Anurag-singh-thakur** [comment]
@samiurprapon hey...how i can get this image which must be kept as you said ...

**Comment by samiurprapon** [comment]
@Anurag-singh-thakur 
You can find the image and the complete design here: [Figma link](https://www.figma.com/design/07DX15asGMIA8VWwTqZYUl/aether?node-id=0-1&t=FS5zurlfhYIFwH9W-1).

Feel free to make any improvements to the design directly on Figma as well.

**Comment by Anurag-singh-thakur** [comment]
@samiurprapon I have meet your complete requirements ..please view and merge it . Thanks for assigning me

**Comment by samiurprapon** [comment]
> @samiurprapon I have met your all the requirements ..please view and merge it . Thanks for assigning me

I have reviewed your PR. Please check I asked for a few changes. And will merge it onwards. Thank you for your contributions.

**Comment by Anurag-singh-thakur** [comment]
@samiurprapon please tell me clearly what you want ...i am still confused its a request please clarify the things

**Comment by samiurprapon** [comment]
@Anurag-singh-thakur, Sorry for the confusion, The Auth page looks identical, the only missing part is the Top bar menu. And Not responsive on mobile devices.

**Comment by Anurag-singh-thakur** [comment]
@samiurprapon i have done .. and also i have improved the ui hope you like it.please review and merge it as soon as possible 
![image](https://github.com/user-attachments/assets/af6e4f87-ece5-421b-9748-8b4ede984d6c)
![image](https://github.com/user-attachments/assets/644e315b-48d1-4312-88c9-4e03ffa7a81f)

**Comment by samiurprapon** [comment]
@Anurag-singh-thakur I have merged your PR #205  . Even though it's not the exact same but was close. Thank you for your contributions ^_^

**Comment by Anurag-singh-thakur** [comment]
Thanks..the reason for not exact is such that you give me the figma link and said you can modify this also so that's why i tried a new UI...
